### ISSUE TITLE
TODO Comment Many Intraday tables

### ISSUE THREAD

**Issue by efrazier** [adswerve/google_analytics_flattener_ga4#10]
"#TODO: risk: we might have many intraday tables and therefore, many Cloud Scheduler jobs, which will waste resources
# we decided to leave it for now and if we observe situations like this, we'll fix the intraday flattener"

I have this exact case because for some reason I didn't check the daily option, but only the streaming option for the BigQuery GA4 config.   So I have a years worth of intraday tables in one project. 

It makes me wonder why this option is even optional in GA4, because it looks to me like you end up losing data by not checking the Daily export.

**Comment by RuslanBergenov** [comment]
@efrazier , I'm sorry about taking long to get back to you. 

intraday flattening flattening is non-default and optional, because we find that most clients mainly analyze their daily tables and few clients enable streaming export in their GA4-BigQuery link. 

When linking GA4 property to BigQuery, we recommend selecting the "daily" option and only selecting "streaming" if you have a strong use case for real-time data.

Does that address your question?

![image](https://user-images.githubusercontent.com/45578394/189000995-dd8c15bb-9fc3-49e5-aea7-caf38940b46a.png)

**Comment by RuslanBergenov** [comment]
We will close the issue for now, but we'll reopen if you have any further questions re: this matter.
